// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkVulU4VNoqb0F14bbJ9ioaHC34-MlfkM',
    appId: '1:627224015618:web:f94ba7318d5bf2286d481b',
    messagingSenderId: '627224015618',
    projectId: 'riceguardapp-c3931',
    authDomain: 'riceguardapp-c3931.firebaseapp.com',
    storageBucket: 'riceguardapp-c3931.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV4U5OsHjr8FnkgKxbvrfm2X89K69BPQk',
    appId: '1:627224015618:android:4d1a34bad84c9a956d481b',
    messagingSenderId: '627224015618',
    projectId: 'riceguardapp-c3931',
    storageBucket: 'riceguardapp-c3931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCkfgx_7dxi9rRBuvrMYr4zONATx1OeU',
    appId: '1:627224015618:ios:5777711d0fda58086d481b',
    messagingSenderId: '627224015618',
    projectId: 'riceguardapp-c3931',
    storageBucket: 'riceguardapp-c3931.appspot.com',
    iosBundleId: 'com.example.riceguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCkfgx_7dxi9rRBuvrMYr4zONATx1OeU',
    appId: '1:627224015618:ios:5777711d0fda58086d481b',
    messagingSenderId: '627224015618',
    projectId: 'riceguardapp-c3931',
    storageBucket: 'riceguardapp-c3931.appspot.com',
    iosBundleId: 'com.example.riceguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkVulU4VNoqb0F14bbJ9ioaHC34-MlfkM',
    appId: '1:627224015618:web:5e7ab469b9e874cd6d481b',
    messagingSenderId: '627224015618',
    projectId: 'riceguardapp-c3931',
    authDomain: 'riceguardapp-c3931.firebaseapp.com',
    storageBucket: 'riceguardapp-c3931.appspot.com',
  );
}
